# Generated by Django 5.1 on 2024-08-28 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_entrepreneur_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='investment_stage',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('series_d', 'Series D')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='org_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='startup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('org_position', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_stage', models.CharField(blank=True, choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('series_d', 'Series D')], max_length=200, null=True)),
                ('investment_focus', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
