# Generated by Django 5.1 on 2024-09-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        ('users', '0004_profile_email_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='entrepreneur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.entrepreneur'),
        ),
    ]
