# Generated by Django 5.1 on 2024-09-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_pitch_entrepreneur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pitch',
        ),
    ]
