# Generated by Django 5.1 on 2024-09-04 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0003_delete_pitch'),
        ('users', '0004_profile_email_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='pitch_images/')),
                ('investment_stage', models.CharField(blank=True, choices=[('none', 'None'), ('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('series_d', 'Series D')], max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.entrepreneur')),
            ],
        ),
    ]
