# Generated by Django 5.1 on 2024-10-15 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0004_initial'),
        ('users', '0004_profile_email_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.investor')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.pitch')),
            ],
        ),
    ]
